# -*- coding: utf-8 -*-
"""CWOP_Station_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpIK8IxQm_1etlfe_rcKTGoFdNuB9D6y
"""

import requests
from datetime import datetime

# --- AUTHORIZED CONFIG ---
TOKEN = "f11b724afdd9436c9f0fc499d257edd1"
NETWORK = "65"  # CWOP Network
FILENAME = "CWOP_V2.txt"
ICON_URL = "https://raw.githubusercontent.com/marsonnen17-ui/NE_CWOP_Placefile/main/wind_barbs_V4_64.png"

# Priority Stations
TARGET_STIDS = ["E7235", "G4507", "C9774", "E7290", "D4989", "E3958", "E7246", "AR970"]

API_URL = f"https://api.synopticdata.com/v2/stations/latest?token={TOKEN}&networks={NETWORK}&units=english"

def get_barb_index(wind_speed_value_1):
    """
    Maps MPH to knots, then to the correct index.
    0-4 knots = Index 1 (Calm)
    5-9 knots = Index 2 (5kts)
    10-14 knots = Index 3 (10kts)
    """
    try:
        # 1. Convert MPH to Knots
        wspd_kts = float(wind_speed_value_1) * 0.868976

        # 2. Force Calm for anything 0-4 knots
        if wspd_kts < 4.5:
            return 2  # Index 1 is the Circle

        # 3. Calculate Index (The +1 ensures we skip the blank Index 0)
        # For 13 knots (15mph): (13 + 2.5) // 5 = 3.  3 + 1 = 4.
        index = int((wspd_kts + 2.5) // 5) + 2

        return min(index, 21)
    except:
        return 2

def build_placefile():
    try:
        response = requests.get(API_URL, timeout=20)
        filtered_stations = [s for s in response.json().get('STATION', []) if s.get('STID') in TARGET_STIDS]

        with open(FILENAME, "w", encoding="utf-8") as f:
            # --- HEADER ---
            f.write("Title: CWOP - Live Plot\n")
            f.write("Refresh: 5\n")
            f.write("Threshold: 999\n")
            # CRUCIAL: Assign Font ID #1 (12 pixels high, Bold=1, Face="Arial")
            f.write('Font: 1, 12, 1, "Arial"\n')
            f.write(f'IconFile: 1, 27, 48, 14, 24, "{ICON_URL}"\n\n')

            for stn in filtered_stations:
                lat, lon = stn.get('LATITUDE'), stn.get('LONGITUDE')
                if not (lat and lon): continue

                stid = stn.get('STID', 'UNK')
                obs = stn.get('OBSERVATIONS', {})
                wspd = obs.get('wind_speed_value_1', {}).get('value', 0)
                wdir = obs.get('wind_direction_value_1', {}).get('value', 0)
                gust = obs.get('wind_gust_value_1', {}).get('value', wspd)
                temp = obs.get('air_temp_value_1', {}).get('value', "N/A")
                dewp = obs.get('dew_point_temperature_value_1', {}).get('value', "N/A")


                # Timestamp Handling
                raw_time = obs.get('air_temp_value_1', {}).get('date_time')
                if raw_time:
                    dt = datetime.strptime(raw_time, "%Y-%m-%dT%H:%M:%SZ")
                    display_time = dt.strftime("%H:%M") + "z"
                else:
                    display_time = "N/A"


                # Format text strings cleanly for the map screen
                try:
                    t_text = f"{int(float(temp))}" if temp != "N/A" else ""
                except: t_text = ""

                try:
                    # Only map a gust string if it exceeds sustained wind speed
                    g_text = f"G{int(float(gust))}" if float(gust) > float(wspd) else ""
                except: g_text = ""

                if lat and lon:
                    idx = get_barb_index(wspd)
                    # Updated Label with Dewpoint
                    label = (f"{stn.get('NAME', stid)}\\n"
                             f"Temp: {temp}F / Dewp: {dewp}F\\n"
                             f"Wind: {int(float(wspd)*1.151)} G {int(float(gust)*1.151)} mph\\n"
                             f"Updated: {display_time}")

                # 1. Plot the Wind Barb Icon right at the center anchor point (0,0 offset)
                    f.write("  Color: 255 255 255\n")
                    f.write(f'  Icon: 0, 0, {int(float(wdir))}, 1, {idx}, "{label}"\n')

                # 2. Plot Temperature Text at Upper Left (-28 pixels X, +14 pixels Y)

                    #f.write("  Color: 255 110 110\n") # Soft red for temperature visibility
                    #f.write(f'  Text: -28, 14, 1, "{int(round(temp))}"\n')

              # 3 Wind Gusts
                    #f.write("  Color: 255 255 100\n") # Bright yellow for attention on gusts
                    #f.write(f'  Text: 28, -14, 1, "G{int(round(gust))}"\n')

            f.write("End:\n\n") # Properly closes out the object group

        print("Placefile with on-screen text metrics written successfully.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    build_placefile()

import requests
from datetime import datetime

# --- AUTHORIZED CONFIG ---
TOKEN = "f11b724afdd9436c9f0fc499d257edd1"
NETWORK = "65"  # CWOP Network
FILENAME = "CWOP_Full_ObsV2.txt"
ICON_URL = "https://raw.githubusercontent.com/marsonnen17-ui/NE_CWOP_Placefile/main/wind_barbs_V4_64.png"

# Priority Stations
TARGET_STIDS = ["E7235", "G4507", "C9774", "E7290", "D4989", "E3958", "E7246", "AR970"]

API_URL = f"https://api.synopticdata.com/v2/stations/latest?token={TOKEN}&networks={NETWORK}&units=english"

def get_barb_index(wind_speed_value_1):
    """
    Maps MPH to knots, then to the correct index.
    0-4 knots = Index 1 (Calm)
    5-9 knots = Index 2 (5kts)
    10-14 knots = Index 3 (10kts)
    """
    try:
        # 1. Convert MPH to Knots
        wspd_kts = float(wind_speed_value_1) * 0.868976

        # 2. Force Calm for anything 0-4 knots
        if wspd_kts < 4.5:
            return 2  # Index 1 is the Circle

        # 3. Calculate Index (The +1 ensures we skip the blank Index 0)
        # For 13 knots (15mph): (13 + 2.5) // 5 = 3.  3 + 1 = 4.
        index = int((wspd_kts + 2.5) // 5) + 2

        return min(index, 21)
    except:
        return 2


def build_placefile():
    try:
        # Fetching network data
        response = requests.get(API_URL, timeout=20)
        data = response.json()
        all_stations = data.get('STATION', [])

        # Filter post-API for your specific locations
        filtered_stations = [s for s in all_stations if s.get('STID') in TARGET_STIDS]

        with open(FILENAME, "w", encoding="utf-8") as f:
            # HEADER
            f.write("Title: NE CWOP - Full Observations V2\n")
            f.write("Refresh: 5\n")
            f.write("Threshold: 999\n")
            f.write('Font: 1, 12, 1, "Arial"\n')
            f.write(f'IconFile: 1, 64, 61, 32, 32, "{ICON_URL}"\n\n')

            for stn in filtered_stations:
                lat, lon = stn.get('LATITUDE'), stn.get('LONGITUDE')
                stid = stn.get('STID', 'UNK')
                obs = stn.get('OBSERVATIONS', {})

                # Extract Wind, Temp, and Dewpoint safely
                wspd = obs.get('wind_speed_value_1', {}).get('value', 0)
                wdir = obs.get('wind_direction_value_1', {}).get('value', 0)
                gust = obs.get('wind_gust_value_1', {}).get('value', wspd)
                temp = obs.get('air_temp_value_1', {}).get('value', "N/A")
                dewp = obs.get('dew_point_temperature_value_1d', {}).get('value', "N/A")

                # Hover label formatting
                raw_time = obs.get('air_temp_value_1', {}).get('date_time')
                display_time = datetime.strptime(raw_time, "%Y-%m-%dT%H:%M:%SZ").strftime("%H:%M") + "z" if raw_time else "N/A"
                label = f"{stn.get('NAME', stid)}\\nT: {temp}F / D: {dewp}F\\nWind: {int(float(wspd)*1.151)} G {int(float(gust)*1.151)} mph\\nUpdated: {display_time}"

                idx = get_barb_index(wspd)

                # --- BEGIN COMPOSITE GRID OBJECT BLOCK ---
                f.write(f"Object: {lat}, {lon}\n")

                # 2. Plot Temperature Text at Upper Left (-14 pixels X, +12 pixels Y)
                if temp:
                    f.write("  Color: 255 255 255\n") # Soft white for temperature visibility
                    f.write(f'  Text: -14, 12, 1, "{int(round(temp))}"\n')

                # Plot dewpoint Text at Lower Left
                if dewp:
                    f.write("  Color: 255 255 255\n") # Soft white for dewpoint visibility
                    f.write(f'  Text: -14, -12, 1, "{int(round(dewp))}"\n')

                # 3. Plot Wind Gust Text at Lower Right (+14 pixels X, -12 pixels Y)
                if gust:
                    f.write("  Color: 255 255 100\n") # Bright yellow for attention on gusts
                    f.write(f'  Text: 14, -12, 1, "{int(float(gust)*1.151)}"\n')

                # 1. Plot the Wind Barb Icon right at the center anchor point (0,0 offset)
                f.write("  Color: 255 255 255\n")
                f.write(f'  Icon: 0, 0, {int(float(wdir))}, 1, 2, "{label}"\n')
                f.write(f'  Icon: 0, 0, {int(float(wdir))}, 1, {idx}, "{label}"\n')

                f.write("End:\n\n") # Properly closes out the object group

        print("Placefile with on-screen text metrics written successfully.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    build_placefile()